import * as fs from 'fs';
import * as path from 'path';
import { Memory, MemoryType } from '../../shared/types';

const MEMORY_FILE_NAME = '.claudelander-memory.md';
const MAX_FILE_SIZE = 8192; // 8KB limit

interface InjectorOptions {
  workingDir: string;
  memories: Memory[];
}

/**
 * Format a date for display in memory file
 */
function formatDate(date: Date): string {
  return date.toISOString().split('T')[0]; // YYYY-MM-DD
}

/**
 * Get section header for a memory type
 */
function getSectionHeader(type: MemoryType): string {
  const headers: Record<MemoryType, string> = {
    decision: '## Decisions',
    error_fix: '## Error Fixes',
    pattern: '## Patterns',
    context: '## Context',
    note: '## Notes',
  };
  return headers[type];
}

/**
 * Group memories by type
 */
function groupByType(memories: Memory[]): Map<MemoryType, Memory[]> {
  const grouped = new Map<MemoryType, Memory[]>();

  for (const memory of memories) {
    const existing = grouped.get(memory.type) || [];
    existing.push(memory);
    grouped.set(memory.type, existing);
  }

  return grouped;
}

/**
 * Generate the memory file content
 */
function generateMemoryFileContent(memories: Memory[]): string {
  if (memories.length === 0) {
    return '';
  }

  const lines: string[] = [
    '# Session Memory',
    '*Auto-generated by ClaudeLander - Do not edit manually*',
    '',
  ];

  // Separate pinned from non-pinned
  const pinnedMemories = memories.filter(m => m.pinned);
  const regularMemories = memories.filter(m => !m.pinned);

  // Add pinned memories section first
  if (pinnedMemories.length > 0) {
    lines.push('## 📌 Pinned (Important)');
    lines.push('');
    for (const memory of pinnedMemories) {
      const dateStr = formatDate(memory.createdAt);
      lines.push(`- [${dateStr}] ${memory.content}`);
    }
    lines.push('');
  }

  // Group regular memories by type
  const grouped = groupByType(regularMemories);

  // Add sections in order: decisions, error_fix, pattern, context, note
  const typeOrder: MemoryType[] = ['decision', 'error_fix', 'pattern', 'context', 'note'];

  for (const type of typeOrder) {
    const typeMemories = grouped.get(type);
    if (typeMemories && typeMemories.length > 0) {
      lines.push(getSectionHeader(type));
      lines.push('');
      for (const memory of typeMemories) {
        const dateStr = formatDate(memory.createdAt);
        lines.push(`- [${dateStr}] ${memory.content}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Trim content to fit within size limit
 */
function trimToSize(content: string, maxSize: number): string {
  if (content.length <= maxSize) {
    return content;
  }

  // Find a good break point (end of a line)
  const trimmed = content.slice(0, maxSize);
  const lastNewline = trimmed.lastIndexOf('\n');

  if (lastNewline > maxSize * 0.5) {
    return trimmed.slice(0, lastNewline) + '\n\n*[Truncated due to size limit]*\n';
  }

  return trimmed + '\n\n*[Truncated due to size limit]*\n';
}

/**
 * Write the memory injection file to the working directory
 */
export function writeMemoryFile(options: InjectorOptions): string | null {
  const { workingDir, memories } = options;

  if (!workingDir || !fs.existsSync(workingDir)) {
    console.error('Working directory does not exist:', workingDir);
    return null;
  }

  const filePath = path.join(workingDir, MEMORY_FILE_NAME);

  // Generate content
  let content = generateMemoryFileContent(memories);

  if (!content) {
    // No memories - remove file if it exists
    try {
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }
    } catch (error) {
      console.error('Failed to remove empty memory file:', error);
    }
    return null;
  }

  // Trim to size limit
  content = trimToSize(content, MAX_FILE_SIZE);

  try {
    fs.writeFileSync(filePath, content, 'utf-8');
    return filePath;
  } catch (error) {
    console.error('Failed to write memory file:', error);
    return null;
  }
}

/**
 * Remove the memory injection file from the working directory
 */
export function removeMemoryFile(workingDir: string): boolean {
  if (!workingDir || !fs.existsSync(workingDir)) {
    return false;
  }

  const filePath = path.join(workingDir, MEMORY_FILE_NAME);

  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      return true;
    }
    return false;
  } catch (error) {
    console.error('Failed to remove memory file:', error);
    return false;
  }
}

/**
 * Check if memory file exists in the working directory
 */
export function memoryFileExists(workingDir: string): boolean {
  if (!workingDir || !fs.existsSync(workingDir)) {
    return false;
  }

  const filePath = path.join(workingDir, MEMORY_FILE_NAME);
  return fs.existsSync(filePath);
}

/**
 * Get the memory file path for a working directory
 */
export function getMemoryFilePath(workingDir: string): string {
  return path.join(workingDir, MEMORY_FILE_NAME);
}
